### ISSUE TITLE
process_wiki使用问题

### ISSUE THREAD

**Issue by yuquanle** [hzhyhx1117/word2vec-for-wiki#2]
哥们，我看你也是python3.X的环境，我在python3.5下使用你github里的process_wiki处理维基百科英文数据集。遇到了以下错误。
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Traceback (most recent call last):
  File "process_wiki.py", line 30, in <module>
    output.write(space.join(text) + '\n')
TypeError: sequence item 0: expected str instance, bytes found

能否指教一下你当时是怎么成功的，非常感谢！

**Comment by AdolHong** [comment]
看我的修改

https://github.com/AdolHong/word2vec-for-wiki/commit/c899dcbd2420ea1e110dbda109e4f7381746b6f6

**Comment by AdolHong** [comment]
@yuquanle  看我的修改。https://github.com/AdolHong/word2vec-for-wiki/commit/c899dcbd2420ea1e110dbda109e4f7381746b6f6

@hzhyhx1117  或许该更新一下code
